final List<String> relationList = [
  'Wife',
  'Father',
  'Mother',
  'Son',
  'Daughter',
  'Brother',
  'Sister',
  'Grandfather',
  'Grandmother',
  'Grandson',
  'Granddaughter',
  'Paternal Uncle',
  'Paternal Aunt',
  'Maternal Uncle',
  'Maternal Aunt',
  'Father-in-law',
  'Mother-in-law',
  'Son-in-law',
  'Daughter-in-law',
  'Brother-in-law',
  'Sister-in-law',
  'Nephew',
  'Niece',
];
