// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOTVYQzdPjLQ6j0hxq0cyMGoNjuKgXSmA',
    appId: '1:355448073369:web:a2db75caf9a3006354dc08',
    messagingSenderId: '355448073369',
    projectId: 'nadiadmaheshwarisamaj-24d98',
    authDomain: 'nadiadmaheshwarisamaj-24d98.firebaseapp.com',
    storageBucket: 'nadiadmaheshwarisamaj-24d98.firebasestorage.app',
    measurementId: 'G-2N12FDKJ7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOK9MlFrg5Dd7U4G6MRXlq2Z2iqUd71GA',
    appId: '1:355448073369:android:6bf773e48d06493554dc08',
    messagingSenderId: '355448073369',
    projectId: 'nadiadmaheshwarisamaj-24d98',
    storageBucket: 'nadiadmaheshwarisamaj-24d98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6WK0wctIMjM3tdxBxEwyV2x5H2kpEdlE',
    appId: '1:355448073369:ios:da597d9d1e2c285854dc08',
    messagingSenderId: '355448073369',
    projectId: 'nadiadmaheshwarisamaj-24d98',
    storageBucket: 'nadiadmaheshwarisamaj-24d98.firebasestorage.app',
    iosBundleId: 'com.nadiadmaheshwari.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6WK0wctIMjM3tdxBxEwyV2x5H2kpEdlE',
    appId: '1:355448073369:ios:f636acf031e7390154dc08',
    messagingSenderId: '355448073369',
    projectId: 'nadiadmaheshwarisamaj-24d98',
    storageBucket: 'nadiadmaheshwarisamaj-24d98.firebasestorage.app',
    iosBundleId: 'com.example.mmsn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOTVYQzdPjLQ6j0hxq0cyMGoNjuKgXSmA',
    appId: '1:355448073369:web:ed0e115c773da9ac54dc08',
    messagingSenderId: '355448073369',
    projectId: 'nadiadmaheshwarisamaj-24d98',
    authDomain: 'nadiadmaheshwarisamaj-24d98.firebaseapp.com',
    storageBucket: 'nadiadmaheshwarisamaj-24d98.firebasestorage.app',
    measurementId: 'G-G7SWTK7P95',
  );
}
